import type { PatternLanguageExample } from "@atlas-patterns/schemas";

export const BASIC = {
  language: "basic",
  code: `10 REM THIRD-PARTY TASK API ADAPTER
20 REM EXTERNAL FIELDS: ID, DESC, COMPLETE
30 REM INTERNAL FIELDS: ID, DESCRIPTION, IS COMPLETED

40 DIM TASKID$(2)
50 DIM DESCRIPTION$(2)
60 DIM COMPLETED(2)

70 EXTERNAL_ID$(1) = "1"
80 EXTERNAL_DESC$(1) = "Finish report"
90 EXTERNAL_COMPLETE(1) = 1

100 EXTERNAL_ID$(2) = "2"
110 EXTERNAL_DESC$(2) = "Call client"
120 EXTERNAL_COMPLETE(2) = 0

130 FOR I = 1 TO 2
140 TASKID$(I) = EXTERNAL_ID$(I)
150 DESCRIPTION$(I) = EXTERNAL_DESC$(I)
160 IF EXTERNAL_COMPLETE(I) = 1 THEN COMPLETED(I) = 1
170 NEXT I

180 FOR I = 1 TO 2
190 PRINT DESCRIPTION$(I);
200 IF COMPLETED(I) = 1 THEN PRINT " - COMPLETED" ELSE PRINT " - PENDING"
210 NEXT I

220 END
`,
} satisfies PatternLanguageExample;